{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMAdgEnrEx1hLPWOT4cy82G",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/touseefyounas/PV_Analysis/blob/dash_app_test/pv_dash_app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from dash import Dash,dcc,html\n",
        "from dash.dependencies import Input, Output\n",
        "import requests\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "import folium\n",
        "from folium.raster_layers import ImageOverlay\n",
        "import plotly.graph_objects as go\n",
        "import dash_bootstrap_components as dbc\n",
        "from dash_bootstrap_templates import load_figure_template\n",
        "import time"
      ],
      "metadata": {
        "id": "1AI1cIlXj6d4"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "app = Dash(__name__,external_stylesheets=[dbc.themes.LUX])\n",
        "\n",
        "app.layout = html.Div([\n",
        "    html.H1('Solar Energy Data Dashboard'),\n",
        "\n",
        "    # Input field for system_capacity\n",
        "    html.Label('Nameplate Capacity (kW):'),\n",
        "    dcc.Input(id='system_capacity',type='number', value=4, min=0.05, max=500000),\n",
        "    html.Br(),\n",
        "    html.Br(),\n",
        "\n",
        "    #Radio Item Selection for the type of module i.e. Standard, Premium, Think Film\n",
        "    html.Label('Module type:'),\n",
        "    dcc.RadioItems(id='module_type',\n",
        "        options=[{'label': 'Standard', 'value':0},\n",
        "         {'label': 'Premium', 'value':1},\n",
        "          {'label': 'Thin Film', 'value':2}],value=0),\n",
        "    html.Br(),\n",
        "    html.Br(),\n",
        "\n",
        "    #Input field for system losses\n",
        "    html.Label('System Losses(%):'),\n",
        "    dcc.Input(id='system_losses',type='number',value=5,min=-5,max=100),\n",
        "    html.Br(),\n",
        "    html.Br(),\n",
        "\n",
        "html.Div([\n",
        "    #Radio Item Selection for the array_type\n",
        "    html.Label('Array Type:'),\n",
        "    dcc.Dropdown(id='array_type',options=[{'label':'Fixed - Open Rack','value':0},\n",
        "     {'label':'Fixed - Roof Mounted','value':1},{'label':'1-Axis','value':2},\n",
        "       {'label':' 1-Axis Backtracking','value':3},{'label':'2-Axis','value':4}],value=1),\n",
        "    html.Br(),\n",
        "    html.Br(),],style={'width':'25%'}),\n",
        "\n",
        "    #Slider for selecting Tilt Angle\n",
        "html.Div([\n",
        "    html.Label('Tilt Angle (0 to 90):'),\n",
        "    dcc.Slider(id='tilt_angle', value=30, min=0, max=90, step=0.5,marks={0: '0°', 45: '45°', 90: '90°'}),\n",
        "    dcc.Input(id='tilt_angle_display', type='text', readOnly=True, style={'border': 'none'}),\n",
        "    html.Br(),html.Br(),],style={'width': '30%'}),\n",
        "\n",
        "    #Slider for selecting Azimuth Angle\n",
        "html.Div([\n",
        "    html.Label('Azimuth Angle (0 to 360):'),\n",
        "    dcc.Slider(id='azimuth_angle',value=180,min=0,max=360,step=1,marks={0: '0°', 90: '90°', 180: '180°', 270: '270°', 360: '360°'}),\n",
        "    dcc.Input(id='azimuth_angle_display', type='text', readOnly=True, style={'border': 'none'}),\n",
        "    html.Br(),html.Br(),],style={'width': '30%'}),\n",
        "\n",
        "    #RadioItems for input selection\n",
        "    dcc.RadioItems(id='input-selection',\n",
        "                   options=[{'label': 'Use Address', 'value': 'address'},\n",
        "                    {'label': 'Use Latitude & Longitude', 'value': 'lat_long'}],value='lat_long'),\n",
        "    html.Br(),\n",
        "    html.Br(),\n",
        "\n",
        "    # Div for the address input section\n",
        "html.Div([\n",
        "        html.Label('Enter Address:'),\n",
        "        dcc.Input(id='address-input', type='text'),\n",
        "        html.Br(),\n",
        "        html.Br(),\n",
        "    ], id='address-section'),\n",
        "\n",
        "    # Div for the lat/long input section\n",
        "html.Div([\n",
        "    html.Label('Enter Latitude:'),\n",
        "    dcc.Input(id='lat-input', type='number', value=33.670491),\n",
        "    html.Br(),\n",
        "    html.Br(),\n",
        "    html.Label('Enter Longitude:'),\n",
        "    dcc.Input(id='long-input', type='number', value=72.995602),\n",
        "    html.Br(),\n",
        "    html.Br(),\n",
        "    ], id='lat-long-section'),\n",
        "\n",
        "#Slider for Inverter Efficiency\n",
        "html.Div([\n",
        "    html.Label('Inverter Efficiency (90% to 99.5%):'),\n",
        "    dcc.Slider(id='inv_eff', value=96, min=90, max=99.5, step=0.5,marks={90: '90%', 99.5: '99.5%'}),\n",
        "    dcc.Input(id='inv_eff_display', type='text', readOnly=True, style={'border': 'none'}),\n",
        "    html.Br(),html.Br(),],style={'width': '25%'})\n",
        "])\n",
        "\n",
        "@app.callback(\n",
        "    Output('address-section', 'style'),\n",
        "    Output('lat-long-section', 'style'),\n",
        "    Input('input-selection', 'value')\n",
        ")\n",
        "def update_input_sections(selected_option):\n",
        "    address_style = {'display': 'block' if selected_option == 'address' else 'none'}\n",
        "    lat_long_style = {'display': 'block' if selected_option == 'lat_long' else 'none'}\n",
        "    return address_style, lat_long_style\n",
        "\n",
        "@app.callback(\n",
        "    Output('tilt_angle_display', 'value'),\n",
        "    Output('azimuth_angle_display', 'value'),\n",
        "    Output('inv_eff_display','value'),\n",
        "    Input('tilt_angle','value'),\n",
        "    Input('azimuth_angle','value'),\n",
        "    Input('inv_eff','value'))\n",
        "def update_slider_value_display(tilt_value, azimuth_value, inv_value):\n",
        "    return f'Tilt Angle: {tilt_value}°', f'Azimuth Angle: {azimuth_value}°',f'Inverter Efficiency:{inv_value}%'\n",
        "\n",
        "@app.callback(\n",
        "    [Output('monthly_df','data'),\n",
        "    Output('hourly_df','data'),\n",
        "    Output('error_message_monthly','children'),\n",
        "    Output('error_message_hourly','children')],\n",
        "    [Input('system_capacity','number'),\n",
        "    Input('module_type','value'),\n",
        "    Input('system_losses','number'),\n",
        "    Input('array_type','value'),\n",
        "    Input('tilt_angle','value'),\n",
        "    Input('azimuth_angle','value'),\n",
        "    Input('lat-input','number'),\n",
        "    Input('long-input','number'),\n",
        "    Input('inv_eff','value')]\n",
        ")\n",
        "def get_pv_data(system_capacity,module_type,system_losses,array_type,tilt_angle,azimuth_angle,lat,lon,inv_eff):\n",
        "  url=\"https://developer.nrel.gov/api/pvwatts/v8\"\n",
        "  api_key=\"Rrm78PdXJt41jDkniLFvy5M2NyFY90cxQd2xGopJ\"\n",
        "  error_message_monthly = None\n",
        "  error_message_hourly = None\n",
        "  params_monthly={'format':'json',\n",
        "        'api_key':api_key,\n",
        "        'system_capacity':system_capacity,\n",
        "        'module_type':module_type,\n",
        "        'losses':system_losses,\n",
        "        'array_type':array_type,\n",
        "        'tilt':tilt_angle,\n",
        "        'azimuth':azimuth_angle,\n",
        "        'lat':lat,\n",
        "        'lon':lon,\n",
        "        'inv_eff':inv_eff\n",
        "  }\n",
        "  params_hourly={'format':'json',\n",
        "        'api_key':api_key,\n",
        "        'system_capacity':system_capacity,\n",
        "        'module_type':module_type,\n",
        "        'losses':system_losses,\n",
        "        'array_type':array_type,\n",
        "        'tilt':tilt_angle,\n",
        "        'azimuth':azimuth_angle,\n",
        "        'lat':lat,\n",
        "        'lon':lon,\n",
        "        'timeframe':'hourly',\n",
        "        'inv_eff':inv_eff\n",
        "  }\n",
        "  response_monthly=requests.get(f\"{url}.json\",params=params_monthly)\n",
        "  time.sleep(3.6)\n",
        "  response_hourly=requests.get(f\"{url}.json\",params=params_hourly)\n",
        "\n",
        "  if response_monthly.status_code==200:\n",
        "    pv_data_monthly=response_monthly.json()\n",
        "    pv_monthly_data=pv_data_monthly['outputs']\n",
        "\n",
        "  else:\n",
        "    error_message_monthly=f\"Error: {response_monthly.status_code} - {response_monthly.text}\"\n",
        "    return None,None,error_message_monthly,None\n",
        "\n",
        "\n",
        "  Months=['January','February','March','April','May','June','July','August','September','October','November','December']\n",
        "  monthly_df=pd.DataFrame(pv_monthly_data)\n",
        "  monthly_df.insert(0,'Month',Months)\n",
        "\n",
        "  if response_hourly.status_code==200:\n",
        "    pv_hourly_data=respons_monthly.json()\n",
        "    hourly_df=pd.DataFrame({'ac':pv_hourly_data['outputs']['ac'],\n",
        "                        'poa':pv_hourly_data['outputs']['poa'],\n",
        "                        'dn':pv_hourly_data['outputs']['dn'],\n",
        "                        'dc':pv_hourly_data['outputs']['dc'],\n",
        "                        'df':pv_hourly_data['outputs']['df'],\n",
        "                        'tamb':pv_hourly_data['outputs']['tamb'],\n",
        "                        'tcell':pv_hourly_data['outputs']['tcell'],\n",
        "                        'wspd':pv_hourly_data['outputs']['wspd'],\n",
        "                        'alb':pv_hourly_data['outputs']['alb']})\n",
        "    for index,_ in enumerate(hourly_df.index):\n",
        "      hour=(index % 24) + 1\n",
        "      julian_day=(index // 24) + 1\n",
        "      week=(index // 168) + 1\n",
        "      hourly_df.at[index,'hour']=hour\n",
        "      hourly_df.at[index,'julianDay']=julian_day\n",
        "      hourly_df.at[index,'week']=week\n",
        "  else:\n",
        "    print(f\"Error: {response_hourly.status_code} - {response_hourly.text}\")\n",
        "    return None,None,None,error_message_hourly\n",
        "  return monthly_df, hourly_df, None, None\n",
        "\n",
        "if __name__ == '__main__':\n",
        "    app.run_server(debug=True)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 672
        },
        "id": "aSqD1X7EkQ8J",
        "outputId": "64b2e935-8759-4eb3-c452-2440c78cd203"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.Javascript object>"
            ],
            "application/javascript": [
              "(async (port, path, width, height, cache, element) => {\n",
              "    if (!google.colab.kernel.accessAllowed && !cache) {\n",
              "      return;\n",
              "    }\n",
              "    element.appendChild(document.createTextNode(''));\n",
              "    const url = await google.colab.kernel.proxyPort(port, {cache});\n",
              "    const iframe = document.createElement('iframe');\n",
              "    iframe.src = new URL(path, url).toString();\n",
              "    iframe.height = height;\n",
              "    iframe.width = width;\n",
              "    iframe.style.border = 0;\n",
              "    iframe.allow = [\n",
              "        'accelerometer',\n",
              "        'autoplay',\n",
              "        'camera',\n",
              "        'clipboard-read',\n",
              "        'clipboard-write',\n",
              "        'gyroscope',\n",
              "        'magnetometer',\n",
              "        'microphone',\n",
              "        'serial',\n",
              "        'usb',\n",
              "        'xr-spatial-tracking',\n",
              "    ].join('; ');\n",
              "    element.appendChild(iframe);\n",
              "  })(8050, \"/\", \"100%\", 650, false, window.element)"
            ]
          },
          "metadata": {}
        }
      ]
    }
  ]
}